services:
- type: web
  name: svelte-static
  env: static
  plan: starter
  buildCommand: npm install && npm run build
  staticPublishPath: public
  envVars:
    - key: PUBLIC_API_KEY
      sync: false
    - key: PUBLIC_API_URL
      sync: false
    - key: PUBLIC_LOCAL_API_URL
      sync: false
